### ISSUE TITLE
Undefined symbol: H5T_NATIVE_SHORT_g

### ISSUE THREAD

**Issue by adam-nielsen** [swillner/netcdf4-js#18]
If you have compiled the `netcdf4` and `hdf5` libraries statically (in my case, because I want to deploy to AWS Lambda), then the module is built but it cannot be loaded due to missing symbols:
```
Error: node_modules/netcdf4/build/Release/netcdf4.node: undefined symbol: H5T_NATIVE_SHORT_g
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:718:18)
    at Module.load (internal/modules/cjs/loader.js:599:32)
```
It turns out this is due to a missing library dependency in `binding.gyp`, and the solution is to specify the dependent library:
```
{
  "targets": [
    {
      "libraries": [
        "-lnetcdf",
        "-lhdf5"       # Must specify
      ],
...
```
I haven't been able to test this with shared libraries (as my environment is only building static ones) but if it doesn't break the shared library build, could this change be included for the benefit of those using static libraries?

**Comment by parro-it** [comment]
I don't think the change could be harmful, especially because hdf5 lib is already a dependency of netcdf, so this change does not add further pre-reqs.
Would you mind doing a PR?

**Comment by adam-nielsen** [comment]
Sorry for the delay with this, PR created.
