### ISSUE TITLE
compile errors running npm install ( node@v12.16.0, npm@6.13.4)

### ISSUE THREAD

**Issue by stepheneb** [swillner/netcdf4-js#24]
macOS 10.15.3

netcdf installed with homebrew:

```
$ brew info netcdf
netcdf: stable 4.7.3 (bottled)
Libraries and data formats for array-oriented scientific data
https://www.unidata.ucar.edu/software/netcdf
/usr/local/Cellar/netcdf/4.7.3_1 (89 files, 5.8MB) *
  Poured from bottle on 2020-02-15 at 15:56:20
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/netcdf.rb
==> Dependencies
```

Summary report from installing:

```
35 warnings and 5 errors generated.
make: *** [Release/obj.target/netcdf4/src/Group.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/stephen/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Darwin 19.3.0
gyp ERR! command "/Users/stephen/.nvm/versions/node/v12.16.0/bin/node" "/Users/stephen/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/stephen/dev/node-cdf/node_modules/netcdf4
gyp ERR! node -v v12.16.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 
npm WARN node-cdf@1.0.0 No description
npm WARN node-cdf@1.0.0 No repository field.
```

Just the five errors.

1.
```
./src/Group.cpp:36:49: error: too few arguments to function call, single argument 'context' was not specified
    constructor.Reset(isolate, tpl->GetFunction());
                               ~~~~~~~~~~~~~~~~ ^
```

2.
```
../src/Group.cpp:118:36: error: too few arguments to function call, single argument 'context' was not specified
        len = args[1]->Uint32Value();
              ~~~~~~~~~~~~~~~~~~~~ ^
/Users/stephen/Library/Caches/node-gyp/12.16.0/include/node/v8.h:2707:3: note: 'Uint32Value' declared here
```

3.
```
../src/Group.cpp:161:44: error: no matching member function for call to 'ToObject'
    v8::Local<v8::Object> array = args[2]->ToObject();
                                  ~~~~~~~~~^~~~~~~~
/Users/stephen/Library/Caches/node-gyp/12.16.0/include/node/v8.h:2672:44: note: candidate function not viable: requires single argument
```

4.
```
../src/Group.cpp:162:88: error: too few arguments to function call, single argument 'context' was not specified
    size_t ndims = array->Get(v8::String::NewFromUtf8(isolate, "length"))->Uint32Value();
```

5.
```
../src/Group.cpp:165:47: error: too few arguments to function call, single argument 'context' was not specified
        dimids[i] = array->Get(i)->Int32Value();
```

The debug.log produced:
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/stephen/.nvm/versions/node/v12.16.0/bin/node',
1 verbose cli   '/Users/stephen/.nvm/versions/node/v12.16.0/bin/npm',
1 verbose cli   'install',
1 verbose cli   'netcdf4'
1 verbose cli ]
2 info using npm@6.13.4
3 info using node@v12.16.0
4 verbose npm-session ed44b6729031d234
5 silly install loadCurrentTree
6 silly install readLocalPackageData
7 http fetch GET 200 https://registry.npmjs.org/netcdf4 17ms (from cache)
8 silly pacote tag manifest for netcdf4@latest fetched in 28ms
9 timing stage:loadCurrentTree Completed in 65ms
10 silly install loadIdealTree
11 silly install cloneCurrentTreeToIdealTree
12 timing stage:loadIdealTree:cloneCurrentTree Completed in 0ms
13 silly install loadShrinkwrap
14 timing stage:loadIdealTree:loadShrinkwrap Completed in 7ms
15 silly install loadAllDepsIntoIdealTree
16 silly resolveWithNewModule netcdf4@0.4.1 checking installable status
17 timing stage:loadIdealTree:loadAllDepsIntoIdealTree Completed in 7ms
18 timing stage:loadIdealTree Completed in 15ms
19 silly currentTree node-cdf@1.0.0
19 silly currentTree ├── iobuffer@3.2.0
19 silly currentTree ├── netcdf-gcms@1.3.1
19 silly currentTree ├── netcdfjs@0.7.0
19 silly currentTree └── utf8@2.1.2
20 silly idealTree node-cdf@1.0.0
20 silly idealTree ├── iobuffer@3.2.0
20 silly idealTree ├── netcdf-gcms@1.3.1
20 silly idealTree ├── netcdf4@0.4.1
20 silly idealTree ├── netcdfjs@0.7.0
20 silly idealTree └── utf8@2.1.2
21 silly install generateActionsToTake
22 timing stage:generateActionsToTake Completed in 3ms
23 silly diffTrees action count 1
24 silly diffTrees add netcdf4@0.4.1
25 silly decomposeActions action count 8
26 silly decomposeActions fetch netcdf4@0.4.1
27 silly decomposeActions extract netcdf4@0.4.1
28 silly decomposeActions preinstall netcdf4@0.4.1
29 silly decomposeActions build netcdf4@0.4.1
30 silly decomposeActions install netcdf4@0.4.1
31 silly decomposeActions postinstall netcdf4@0.4.1
32 silly decomposeActions finalize netcdf4@0.4.1
33 silly decomposeActions refresh-package-json netcdf4@0.4.1
34 silly install executeActions
35 silly doSerial global-install 8
36 verbose correctMkdir /Users/stephen/.npm/_locks correctMkdir not in flight; initializing
37 verbose lock using /Users/stephen/.npm/_locks/staging-db43c5e244f989ba.lock for /Users/stephen/dev/node-cdf/node_modules/.staging
38 silly doParallel extract 1
39 silly extract netcdf4@0.4.1
40 silly tarball trying netcdf4@latest by hash: sha512-XU2uEKh7N6jzJUSqJGEm0C6f92ea3WrRXnGa4bcRh2jq9lKD2H1OCGxjjzKPjD31z15qL5S9y342gfeui/Uu3A==
41 silly extract netcdf4@latest extracted to /Users/stephen/dev/node-cdf/node_modules/.staging/netcdf4-73e7ef9a (205ms)
42 timing action:extract Completed in 208ms
43 silly doReverseSerial unbuild 8
44 silly doSerial remove 8
45 silly doSerial move 8
46 silly doSerial finalize 8
47 silly finalize /Users/stephen/dev/node-cdf/node_modules/netcdf4
48 timing action:finalize Completed in 2ms
49 silly doParallel refresh-package-json 1
50 silly refresh-package-json /Users/stephen/dev/node-cdf/node_modules/netcdf4
51 timing action:refresh-package-json Completed in 6ms
52 silly doParallel preinstall 1
53 silly preinstall netcdf4@0.4.1
54 info lifecycle netcdf4@0.4.1~preinstall: netcdf4@0.4.1
55 timing action:preinstall Completed in 1ms
56 silly doSerial build 8
57 silly build netcdf4@0.4.1
58 info linkStuff netcdf4@0.4.1
59 silly linkStuff netcdf4@0.4.1 has /Users/stephen/dev/node-cdf/node_modules as its parent node_modules
60 timing action:build Completed in 1ms
61 silly doSerial global-link 8
62 silly doParallel update-linked 0
63 silly doSerial install 8
64 silly install netcdf4@0.4.1
65 info lifecycle netcdf4@0.4.1~install: netcdf4@0.4.1
66 verbose lifecycle netcdf4@0.4.1~install: unsafe-perm in lifecycle true
67 verbose lifecycle netcdf4@0.4.1~install: PATH: /Users/stephen/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/stephen/dev/node-cdf/node_modules/netcdf4/node_modules/.bin:/Users/stephen/dev/node-cdf/node_modules/.bin:/Users/stephen/.nvm/versions/node/v12.16.0/bin:/Users/stephen/.rbenv/shims:/usr/local/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/share/dotnet:/opt/X11/bin:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands:/Applications/Xamarin Workbooks.app/Contents/SharedSupport/path-bin:/Users/stephen/dev/bin
68 verbose lifecycle netcdf4@0.4.1~install: CWD: /Users/stephen/dev/node-cdf/node_modules/netcdf4
69 silly lifecycle netcdf4@0.4.1~install: Args: [ '-c', 'node-gyp rebuild' ]
70 timing audit submit Completed in 667ms
71 http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/audits/quick 667ms
72 timing audit body Completed in 1ms
73 silly lifecycle netcdf4@0.4.1~install: Returned: code: 1  signal: null
74 info lifecycle netcdf4@0.4.1~install: Failed to exec install script
75 timing action:install Completed in 2281ms
76 verbose unlock done using /Users/stephen/.npm/_locks/staging-db43c5e244f989ba.lock for /Users/stephen/dev/node-cdf/node_modules/.staging
77 timing stage:rollbackFailedOptional Completed in 70ms
78 timing stage:runTopLevelLifecycles Completed in 2696ms
79 silly saveTree node-cdf@1.0.0
79 silly saveTree ├─┬ netcdf-gcms@1.3.1
79 silly saveTree │ └─┬ netcdfjs@0.7.0
79 silly saveTree │   └─┬ iobuffer@3.2.0
79 silly saveTree │     └── utf8@2.1.2
79 silly saveTree └── netcdf4@0.4.1
80 warn node-cdf@1.0.0 No description
81 warn node-cdf@1.0.0 No repository field.
82 verbose stack Error: netcdf4@0.4.1 install: `node-gyp rebuild`
82 verbose stack Exit status 1
82 verbose stack     at EventEmitter.<anonymous> (/Users/stephen/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
82 verbose stack     at EventEmitter.emit (events.js:321:20)
82 verbose stack     at ChildProcess.<anonymous> (/Users/stephen/.nvm/versions/node/v12.16.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
82 verbose stack     at ChildProcess.emit (events.js:321:20)
82 verbose stack     at maybeClose (internal/child_process.js:1021:16)
82 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
83 verbose pkgid netcdf4@0.4.1
84 verbose cwd /Users/stephen/dev/node-cdf
85 verbose Darwin 19.3.0
86 verbose argv "/Users/stephen/.nvm/versions/node/v12.16.0/bin/node" "/Users/stephen/.nvm/versions/node/v12.16.0/bin/npm" "install" "netcdf4"
87 verbose node v12.16.0
88 verbose npm  v6.13.4
89 error code ELIFECYCLE
90 error errno 1
91 error netcdf4@0.4.1 install: `node-gyp rebuild`
91 error Exit status 1
92 error Failed at the netcdf4@0.4.1 install script.
92 error This is probably not a problem with npm. There is likely additional logging output above.
93 verbose exit [ 1, true ]

```

**Comment by PhilipNelson5** [comment]
I am getting the same errors on
* centos 7
* node v12.14.0
* npm 6.13.4
* node-gyp v5.0.5

Has there been any progress?
