### ISSUE TITLE
err with node-gyp rebuild

### ISSUE THREAD

**Issue by abe732** [swillner/netcdf4-js#5]
Hey there! Not sure if it's an issue with the package, but I get an err with node-gyp rebuild where it says it can't find the file netcdf.h. I've got the proper netcdf-c version installed on my computer and can access it using the command line (originally had thought it might be that it couldn't locate the netcdf program).

I looked around online and it seems like it's come up in other npm packages; tried the usual suggestions of updating node, deleting node_modules and re-installing, etc. etc.

Thought I'd flag in case you might be able to assist. Here's the actual error:

> node-gyp rebuild

  CXX(target) Release/obj.target/netcdf4/src/Group.o
In file included from ../src/Group.cpp:3:
../src/Variable.h:4:10: fatal error: 'netcdf.h' file not found
#include <netcdf.h>
         ^
1 error generated.
make: *** [Release/obj.target/netcdf4/src/Group.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:204:12)
gyp ERR! System Darwin 16.1.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/AdamBehrens/coding/as-clear-sky/node_modules/netcdf4
gyp ERR! node -v v6.0.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok

**Comment by swillner** [comment]
Hmm, CXX seems to be unable to find your netcdf.h.
Try
```
export CPATH="$CPATH:/path/to/folder/including/netcdfh"
```
before installing...

**Comment by swillner** [comment]
Dear @pomarc,
Unfortunately, I do not have any experience of using node/npm/node-gyp on Windows. You could try to override the CXX environment variable to something like "msbuild /useenv", though. What is CXX set to on WIndows?

**Comment by swillner** [comment]
closing due to inactivity
